<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.GmKRqWU' shared service.

return $this->privates['.service_locator.GmKRqWU'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'filmRepo' => ['privates', 'App\\Repository\\FilmRepository', 'getFilmRepositoryService.php', true],
    'historiqueM' => ['privates', 'App\\Repository\\HistoriqueMembreRepository', 'getHistoriqueMembreRepositoryService.php', true],
    'mRepo' => ['privates', 'App\\Repository\\MembreRepository', 'getMembreRepositoryService.php', true],
    'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
], [
    'filmRepo' => 'App\\Repository\\FilmRepository',
    'historiqueM' => 'App\\Repository\\HistoriqueMembreRepository',
    'mRepo' => 'App\\Repository\\MembreRepository',
    'manager' => '?',
]);
