<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.eHkkt9o' shared service.

return $this->privates['.service_locator.eHkkt9o'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'filmrepos' => ['privates', 'App\\Repository\\FilmRepository', 'getFilmRepositoryService.php', true],
    'repository' => ['privates', 'App\\Repository\\GenreRepository', 'getGenreRepositoryService.php', true],
], [
    'filmrepos' => 'App\\Repository\\FilmRepository',
    'repository' => 'App\\Repository\\GenreRepository',
]);
