<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.SlLPPJO' shared service.

return $this->privates['.service_locator.SlLPPJO'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\AdminController::AddAbo' => ['privates', '.service_locator.sE7Usfg', 'get_ServiceLocator_SE7UsfgService.php', true],
    'App\\Controller\\AdminController::AjouteFilm' => ['privates', '.service_locator.NXXJFvx', 'get_ServiceLocator_NXXJFvxService.php', true],
    'App\\Controller\\AdminController::DeleteAbo' => ['privates', '.service_locator._gyvIPn', 'get_ServiceLocator_GyvIPnService.php', true],
    'App\\Controller\\AdminController::HistoriqueMembre' => ['privates', '.service_locator.QyWrY7j', 'get_ServiceLocator_QyWrY7jService.php', true],
    'App\\Controller\\AvisFilmController::AjouteAvis' => ['privates', '.service_locator.GmKRqWU', 'get_ServiceLocator_GmKRqWUService.php', true],
    'App\\Controller\\AvisFilmController::DisplayAvis' => ['privates', '.service_locator.IEhCfJr', 'get_ServiceLocator_IEhCfJrService.php', true],
    'App\\Controller\\RechercheController::RechercheDst' => ['privates', '.service_locator.LyVulC8', 'get_ServiceLocator_LyVulC8Service.php', true],
    'App\\Controller\\RechercheController::RechercheFilmDate' => ['privates', '.service_locator.bzczM7g', 'get_ServiceLocator_BzczM7gService.php', true],
    'App\\Controller\\RechercheController::RechercheGenre' => ['privates', '.service_locator.eHkkt9o', 'get_ServiceLocator_EHkkt9oService.php', true],
    'App\\Controller\\AdminController:AddAbo' => ['privates', '.service_locator.sE7Usfg', 'get_ServiceLocator_SE7UsfgService.php', true],
    'App\\Controller\\AdminController:AjouteFilm' => ['privates', '.service_locator.NXXJFvx', 'get_ServiceLocator_NXXJFvxService.php', true],
    'App\\Controller\\AdminController:DeleteAbo' => ['privates', '.service_locator._gyvIPn', 'get_ServiceLocator_GyvIPnService.php', true],
    'App\\Controller\\AdminController:HistoriqueMembre' => ['privates', '.service_locator.QyWrY7j', 'get_ServiceLocator_QyWrY7jService.php', true],
    'App\\Controller\\AvisFilmController:AjouteAvis' => ['privates', '.service_locator.GmKRqWU', 'get_ServiceLocator_GmKRqWUService.php', true],
    'App\\Controller\\AvisFilmController:DisplayAvis' => ['privates', '.service_locator.IEhCfJr', 'get_ServiceLocator_IEhCfJrService.php', true],
    'App\\Controller\\RechercheController:RechercheDst' => ['privates', '.service_locator.LyVulC8', 'get_ServiceLocator_LyVulC8Service.php', true],
    'App\\Controller\\RechercheController:RechercheFilmDate' => ['privates', '.service_locator.bzczM7g', 'get_ServiceLocator_BzczM7gService.php', true],
    'App\\Controller\\RechercheController:RechercheGenre' => ['privates', '.service_locator.eHkkt9o', 'get_ServiceLocator_EHkkt9oService.php', true],
], [
    'App\\Controller\\AdminController::AddAbo' => '?',
    'App\\Controller\\AdminController::AjouteFilm' => '?',
    'App\\Controller\\AdminController::DeleteAbo' => '?',
    'App\\Controller\\AdminController::HistoriqueMembre' => '?',
    'App\\Controller\\AvisFilmController::AjouteAvis' => '?',
    'App\\Controller\\AvisFilmController::DisplayAvis' => '?',
    'App\\Controller\\RechercheController::RechercheDst' => '?',
    'App\\Controller\\RechercheController::RechercheFilmDate' => '?',
    'App\\Controller\\RechercheController::RechercheGenre' => '?',
    'App\\Controller\\AdminController:AddAbo' => '?',
    'App\\Controller\\AdminController:AjouteFilm' => '?',
    'App\\Controller\\AdminController:DeleteAbo' => '?',
    'App\\Controller\\AdminController:HistoriqueMembre' => '?',
    'App\\Controller\\AvisFilmController:AjouteAvis' => '?',
    'App\\Controller\\AvisFilmController:DisplayAvis' => '?',
    'App\\Controller\\RechercheController:RechercheDst' => '?',
    'App\\Controller\\RechercheController:RechercheFilmDate' => '?',
    'App\\Controller\\RechercheController:RechercheGenre' => '?',
]);
