<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.NXXJFvx' shared service.

return $this->privates['.service_locator.NXXJFvx'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'filmMembre' => ['privates', 'App\\Repository\\FilmRepository', 'getFilmRepositoryService.php', true],
    'historiqueMembre' => ['privates', 'App\\Repository\\HistoriqueMembreRepository', 'getHistoriqueMembreRepositoryService.php', true],
], [
    'filmMembre' => 'App\\Repository\\FilmRepository',
    'historiqueMembre' => 'App\\Repository\\HistoriqueMembreRepository',
]);
