<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCGjtE3u\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCGjtE3u/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCGjtE3u.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCGjtE3u\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerCGjtE3u\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'CGjtE3u',
    'container.build_id' => 'ec13451d',
    'container.build_time' => 1563201846,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCGjtE3u');
